# Generated by Django 2.2.24 on 2024-08-06 19:38

from django.db import migrations


def move_body(apps, schema_editor):
    Post = apps.get_model('property', 'Flat')
    for post in Post.objects.all():
        if post.construction_year >= 2015:
            post.new_building = True
            post.save()
        else:
            post.new_building = False
            post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(move_body)
    ]
