# Generated by Django 2.2.24 on 2024-08-07 13:08
import phonenumbers
from django.db import migrations


def move_phone(apps, schema_editors):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


def reverse_move_phone(apps, schema_editors):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().update(new_building=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(move_phone, reverse_move_phone)
    ]
