# Generated by Django 2.2.24 on 2024-08-07 13:08
import phonenumbers
from django.db import migrations


def move_phone(apps, schema_editors):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        number_parse = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        final_number = phonenumbers.format_number(number_parse, phonenumbers.PhoneNumberFormat.E164)
        Flat.objects.filter(id=flat.id).update(owner_pure_phone=final_number)


def reverse_move_phone(apps, schema_editors):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update_or_create(owner_pure_phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(move_phone, reverse_move_phone)
    ]
