# Generated by Django 2.2.24 on 2024-08-08 17:41

from django.db import migrations


def get_owner_details(apps, schema_editors):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        owner, created = Owner.objects.update_or_create(name=flat.owner,
                                                        owners_phonenumber=flat.owners_phonenumber,
                                                        owner_pure_phone=flat.owner_pure_phone)
        owner.apartments_ownership.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(get_owner_details)
    ]
