# Generated by Django 2.2.24 on 2024-08-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20240808_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='apartments_ownership',
            field=models.ManyToManyField(db_index=True, related_name='owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
